#!/bin/bash
# Script made by Aaron Vigal. http://www.aaronvigal.com

mkdir /usr/share/csctk
# Download needed files from github
git clone https://github.com/MWHSCSC-ORG/CSCTK.git /usr/share/csctk
# Add alias
echo "alias 'csctk'=/usr/share/csctk/./main" >> ~/.bashrc
echo "deb-src http://security.kali.org/kali-security kali/updates main contrib non-free" >> /etc/apt/sources.list
# Install dependencies
sudo apt-get -y install at>/dev/null 
sudo apt-get -y install libnotify-bin>/dev/null 
sudo apt-get install python3-pip
pip3 install beautifulsoup4
pip3 install selenium
pip3 install argparse
# Make file executable
sudo chmod +x /usr/share/csctk/main 
sudo chmod +x /usr/share/csctk/loading10
sudo chmod +x /usr/share/csctk/loading15
# Remove setup file
rm setup
notify-send "CSCTK is done installing :)"
