#!/bin/bash
# Script made by Aaron Vigal. http://www.aaronvigal.com

mkdir /usr/share/aaronstoolkit
# Download needed files from github
git clone https://github.com/AaronVigal/aaronstoolkit.git /usr/share/aaronstoolkit
# Install dependencies
sudo apt-get -y install libnotify-bin>/dev/null 
sudo apt-get install cron
wget http://download.aircrack-ng.org/aircrack-ng-1.2-beta3.tar.gz
tar xzf aircrack-ng-1.2-beta3.tar.gz
cd aircrack-ng-1.2-beta3
make
curl -L https://get.rvm.io | bash -s stable
source ~/.rvm/scripts/rvm
echo "source ~/.rvm/scripts/rvm" >> ~/.bashrc
source ~/.bashrc
rvm install 2.1.9
rvm use 2.1.9 --default
sudo apt-get install build-essential libreadline-dev libssl-dev libpq5 libpq-dev libreadline5 libsqlite3-dev libpcap-dev openjdk-7-jre git-core autoconf postgresql pgadmin3 curl zlib1g-dev libxml2-dev libxslt1-dev vncviewer libyaml-dev curl zlib1g-dev
cd /opt
sudo git clone https://github.com/rapid7/metasploit-framework.git
sudo chown -R `whoami` /opt/metasploit-framework
cd metasploit-framework
rvm --default use ruby-2.1.6@metasploit-framework
cd metasploit-framework
sudo bash -c 'for MSF in $(ls msf*); do ln -s /opt/metasploit-framework/$MSF /usr/local/bin/$MSF;done'
gem install bundler
bundle install

# Make file executable
sudo chmod +x /usr/share/aaronstoolkit/main 
# Add alias
echo "alias 'aaronstoolkit'=/usr/share/aaronstoolkit/./main" >> ~/.bashrc
# Remove setup file
rm setup_other
notify-send "AaronsToolkit is done installing :)"
